export const STORE_TOKEN = 'STORE_TOKEN';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';
export const STORE_USER_DATA = 'STORE_USER_DATA';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';
export const STORE_USER_STATS = 'STORE_USER_STATS';
export const FETCH_USER_STATS_FAILED = 'FETCH_USER_STATS_FAILED';

export const FETCH_ACTIVITIES_START = 'FETCH_ACTIVITIES_START';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const FETCH_ACTIVITIES_FAILED = 'FETCH_ACTIVITIES_FAILED';

export const FETCH_ACTIVITY_START = 'FETCH_ACTIVITY_START';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const FETCH_ACTIVITY_FAILED = 'FETCH_ACTIVITY_FAILED';